apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-secrets-config-notificaciones
  namespace: studio-barber
spec:
  provider: gcp
  parameters:
    # La KSA utiliza esta GSA para la autenticaci√≥n
    serviceAccount: noti-permissions@studiobarber-480215.iam.gserviceaccount.com
  secretObjects:
    - secretName: sengrid-k8s
      type: Opaque
      data:

        - key: SENDGRID_API_KEY
          objectName: noti-sengrid-api-key

        - key: SENDGRID_NAME
          objectName: noti-sengrid-name

        - key: SENDGRID_EMAIL
          objectName: noti-sengrid-email

        - key: URL_NOTIFICACION
          objectName: pagos-notificacion-url